### ISSUE TITLE
Refactor Klines Provider <> Orderbook Frontend

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1032]
## 📝 Feedback Description

This issue is all about the removal of Klines Provider. Rather, We will create a helper function to fetch candles data. We will handle realtime subscription for graph in Subscription Provider which was already created. 

## ☑ Tasks - 

- [x] Remove the klines provider completely

- [x] Create a new helper function `fetchCandles()` which provide graph data

- [x] Handle realtime subscription for graph

## 🌍 Your Environment

| Software         | Version(s)                  |
| :----------------: | :---------------------------: |
| Project/Package  |      Orderbook Frontend                       |
| Browser          | [x] Chrome [] Firefox [] Safari |
| Operating System | [x] Windows [] MacOS [] Linux   |
