### ISSUE TITLE
History and Balances Components in Hesta Version <> Orderbook Frontend

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1049]
## 📝 Feature Description

In Hestia Version of Orderbook, We need to create table components for showing Open Orders, Order History, Trade History and Balances. 

## ✅ Tasks - 

- [x] Open Orders Component
- [x] Order History Component supported by Infinite Scroll
- [x] Trade History Component supported by Infinite Scroll
- [x] Balances Table Component
- [x] Responsive Tables
- [x] Filters for Open Orders, Order History & Trade History
