### ISSUE TITLE
Deposit and Withdraw Provider <> Orderbook Frontend

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1061]
## 📝 Feedback Description

In current orderbook, We have two providers called `DepositProvider` & `WithdrawProvider`. We will be going to remove these two providers and create three new hooks called `useDeposit`, `useWithdraw`, `useWithdrawClaim` which would be supported by react-query and makes code clean and easy to understand.

## ✅ Tasks 

- [x] Create & Integrate `useDeposit` hook
- [x] Create & Integrate `useWithdraw` hook 
- [x] Create `useWithdrawClaim` hook
- [ ] Integrate `useWithdrawClaim` hook (TODO: Once OB v2 is ready for it)
- [x] Remove Deposit Provider
- [ ] Remove Withdrawal Provider (TODO: Once OB v2 is ready for it)

## 🌍 Your Environment

| Software         | Version(s)                  |
| :----------------: | :---------------------------: |
| Project/Package  |             Orderbook Frontend                |
| Browser          | [x] Chrome [] Firefox [] Safari |
| Operating System | [x] Windows [] MacOS [] Linux   |
