### ISSUE TITLE
Refactor Orders Provider <> Orderbook Frontend

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1086]
## 📝 Feedback Description

As of now, The logic for placing and cancalling the order is in Orders Provider. But, we will be refactoring this for uniformity in project. Our most of the data querying logic is in Orderbook Service, so we will be putting the core logic for placing & cancelling the order in Orderbook Service and will create two hooks to access those methods.

## ✅ Tasks 

- [x] Create methods for placing and cancellng the order inside Orderbook Service
- [x] Create two new hooks which calls newly created methods in Orderbook Service
- [x] Integrate the new hooks 
- [x] CleanUp Orders Provider
- [x] Make Build Successful for both projects (hestia and old UI)

## 🌍 Your Environment

| Software         | Version(s)                  |
| :----------------: |  :---------------------------: |
| Project/Package  |                     Orderbook Frontend        |
| Browser          | [x] Chrome [] Firefox [] Safari |
| Operating System | [] Windows [x] MacOS [] Linux   |
