### ISSUE TITLE
Add Ticker & History Table Feedback <> Orderbook Hestia

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1089]
## 📝 Description

In Open Orders, Order History & Trade History tables on exchange page and history page, we need to show ticker for price, amount, filled, avg. price columns and there should be enhancement in it's responsive view. On adding ticker to these fields, it may looks unresponsive even for larger screens. 

Here are some of the images how Kucoin is handling the responsiveness - 

![image (1)](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/084393e4-4442-480e-89a6-90ca199c11ec)

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/f013ccf3-ca1e-4966-a2b4-9d30a1c7c92e)

Also, Fee component should be fixed, it should show 0.1% taker & maker fee for time being with correct ticker.

## ✅ Tasks -

- [x] Add ticker for all history tables available in Trading Page & History Page
- [x] Fix Trading Fee component
- [x] Fix history tables in History page (Add Filled bar and cancel order enhancement similar to exchange page)

## 🌍 Your Environment

| Software         | Version(s)                  |
| :----------------: | :---------------------------: |
| Project/Package  |           Orderbook Hestia                  |
| Browser          | [x] Chrome [] Firefox [] Safari |
| Operating System | [] Windows [x] MacOS [] Linux   |
