### ISSUE TITLE
Notifications Window <> Orderbook Frontend

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1104]
## 📝 Feature Description

In hestia version of orderbook, we have a component to display different kind of notifications. As of now, that window shows raw data. Now, We will be showing real data for a specific user there. There could be different categories and notifications would be stored in localStorage of browser. 

<img width="1920" alt="image" src="https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/474323f8-deb4-4520-8f15-9dd2161a0c94">

## 🤔 Scenarios 

1. When user place the order ✅
2. When user cancel the order ✅
3. When order gets partially filled for a user ✅
4. When order gets fully filled ✅
5. When a user transfer funds to trading account ✅
6. When a user transfer funds back to funding account ✅
7. When a user transfer funds to any custom account ✅
8. When any transaction is ready to claim ✅
9. When a new trading account created ✅
10. When a trading account removed from blockchain ✅

## ✅ Tasks

- [x] Create a scalable schema to display different kind of categories
- [x] Store all kind of notifications in localStorage
- [x] Display different categories and thier notifications in notification window
- [x] CleanUp the settings provider and remove the duplicate functionalities
- [x] Remove Notification, Mark As Read and Mark All Read notification functionality
