### ISSUE TITLE
Open Beta Fixes <> Orderbook Hestia

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1144]
## 📝 Bug Description

There are some bugs reported in new hestia version of orderbook. In this issue, we will be resolving those - 

- [x] Fix validation of Limit Buy order [Open Beta 631](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/issues/631)

- [x] Persist state for choose filter in Footer [Open Beta 637](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/issues/637)

- [x] All the tables which have some units in any of the column, sorting is not working for them. We will be fixing all the tables here. [Open Beta 634](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/issues/634)

- [x] Select asset on transfer dropdown in place order component [Open Beta 639](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/issues/639)

- [x] Make full button clickable instead of just icon [Open Beta 641](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/issues/641)
