### ISSUE TITLE
Integration of Direct Deposit & Withdrawal

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1330]
## 📝 Description

We have already created packages for enabling direct deposits and withdrawal. Now, next task is to integrate them with UI so that direct deposits/withdrawal could be done from UI.

With Direct deposit, we can deposit tokens from any foreign chain to polkadex orderbook.
With Direct withdraw, we can withdraw tokens from polkadex orderbook to any foreign chain.

## Tasks - 

- [x] Depost Provider Integration
- [x] Withdraw Provider Integration
- [x] Validations for Deposits and withdrawals
- [x] Confirm transaction component
- [x] URL query to choose deposit/withdraw tab
- [x] Minor style fixes
- [x] Integrate History component
- [ ] Direct Withdraw when using extension proxy account
