### ISSUE TITLE
Refactoring pages/_app.tsx

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#576]
**Description  -**

This issue is a part of CleanUp & Optimization Issue for Orderbook. We are cleaning _app.tsx to make code more readable and performative. With this, Duplicacy of code in _app.tsx would be removed.

**Task -** 

- [x] Clean `ThemeWrapper` function and move context/state related code to provider file
- [x] Check `useInit` hook used in ThemeWrapper
- [x] Check if any other code cleaning possibility is there
