### ISSUE TITLE
Lazy Loading of Components in Pages in Orderbook

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#581]
**Description -** 

As we have moved to NextJS v13, we are good to use features of it. One of the main feature of NextJS v13 is to loading components lazily with some loading component/skeleton that will help to improve overall page loading and will improve performance.

**Task -** 
- [x] Find components which would be lazily loaded
- [x] Decide loading skeleton for those components
- [x] Implement the lazy loading for all the choosen components
- [x] Code cleaning and remove all errors and warnings
