### ISSUE TITLE
Flickering Issue in Orderbook

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#598]
**Description -** 

In Orderbook, Starting from Landing page to various other pages/components, whenever one clicks on any button or Component, there is a lot of flickering in other components. This seems so buggy and non-performative to a user. 

https://user-images.githubusercontent.com/65214523/235598787-9ae72363-3609-4911-8738-7139872187c4.webm

**Solution -**

This problem was due to defining fonts along with Global StyleSheet. So, We will be defining fonts and preload them before loading Global StyleSheet and Cached it in headers in next.config.js. 

[Resolved Flicker.webm](https://user-images.githubusercontent.com/65214523/235626376-068c465c-1832-41ff-a12d-fb2fd5a0d47c.webm)

**Tasks -** 

- [x] Define the fonts before defining the global style sheet
- [x] Preload all the fonts
- [x] Put Cache-Control for fonts in next.config.js
- [x] Code Cleaning
