### ISSUE TITLE
Issues with the orders 

### ISSUE THREAD

**Issue by RuchiRay** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#601]
### Problems

- The cancel order button in the open orders section does not work
- After the cancellation , the changes are not immediately shown on the UI , we need to refresh the page for the changes to be displaced.
- if we open any order , it is not displayed in the open orders section immediately, it is shown after we refresh the page

### Task

- [x] Add the orders provider
- [x] Show the cancellation changes immediately 
- [x] Show the open orders when they are created and not after refreshing the page
