### ISSUE TITLE
CSS fixes in Menu and Market Order Component in Orderbook

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#606]
**Description -** 

1. Accounts and Balances Button must be disabled in Side MenuBar. 
2. Side Menu Bar Buttons must be disabled when User is on that page itself. For example, if any user is on Balance page, Balance Button on SideMenu must be disabled.
3. When one goes from trading page to another page, SideMenu Bar Height change which is unexpected. 
4. In Market Order Component, When Dropdown is being opened, there is some flickering in that DropDown only. 

https://user-images.githubusercontent.com/65214523/235884883-6e26f514-6f32-4aa7-afa6-6e75f9e2770f.webm

**Solution -** 

https://user-images.githubusercontent.com/65214523/236013061-3b490de9-b010-4b10-969a-2b9ebe5f8cc7.mp4

**Tasks -** 

- [x] Disable Accounts and Balance Button in SideMenu When User is not logged in
- [x] Disable Specific button on MenuBar if User is on that page itself
- [x] Prevent Height change on Side MenuBar when Page changes
- [x] Stop Flickering of DropDown in Market Order Component
