### ISSUE TITLE
PoC for making Transaction

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#611]
**Description -** 

Learning Task - 

Create a documentation based on Learnings & Develop a Dashboard which can do transactions and show user balances using Polkadot.JS address. 

Here is the link to documentation - [Documentation](https://docs.google.com/document/d/1wK6k7lZR_5gk8Y6_dASgNhdMJAGkC7E78WJzvSgfdYM/edit?usp=sharing)

Here is the link to GH Repo - [Repo](https://github.com/ap211unitech/PoC-for-transaction)

Here is the demo video - 

https://user-images.githubusercontent.com/65214523/236776872-ae0d91bd-af09-44d1-8449-afb35c89f0d4.mp4

**Tasks -** 
- [x] Develop a Dashboard which can show Balances of a sender and do transaction to any valid reciever
- [x] Read about rxjs and how Polkadot.JS uses it
- [x] Update PoC accordingly
