### ISSUE TITLE
UI Fixes in Orderbook

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#619]
**Description -**
 
There are some issues in Ordebook. 

1. Position of tooltip when hovering on menu buttons does not seems correct. Earlier, it was different.
2. On clicking on avatar change, menubar shifts upward
3. On active menu link, add a left border

https://user-images.githubusercontent.com/65214523/237015834-fabcfa67-89ba-4aba-9e40-c3205b9b7f6a.mp4

**Solution -**

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/cdc6bb9b-83a7-43d1-9d62-9e4cfec54107

**Tasks -**

- [x]  Fix Position of tooltip as it was was earlier
- [x] Prevent MenuBar Shifting upward when Click on Avatar Change Button
- [x] Add Left Border on Active Menu Link
