### ISSUE TITLE
Integration of Trading View

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#633]
**Description -**
 
Now, We have the Licensed Trading View. So, We will integrate Trading View with that.

**Tasks -** 

- [x] Integrate Trading View (Licensed) for any sample data
- [x] Display Live Data of Polkadex in Trading View
- [x] UI enhancements (Will discuss with @minikas and will list them)
