### ISSUE TITLE
Integration of Polkadex Data to Trading View Chart

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#634]
**Description -** 

Trading View is already integrated with sample data. In this issue, Polkadex Live Data would be integrated with Trading View. Later on, there is some code re-structuring would be done for clean and concise code. Alogn with it, There are various fixes to be done for performative Trading View.

**Final Look -** 

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/487c7ac5-554c-47a5-8ba6-5e52bdef04b3)

**Tasks -** 

- [x] Integrate the Trading View with Polkadex Data
- [x] Integrate Volume Plane in Trading View
- [x] Code Re-Structuring and cleaning

**Fixes-** 

- [x] Resolve Recursive calls in Trading View to Fetch Data
- [x] Minutes Resolution not working in Trading View
- [x] Resolve Data fetching from Selecting Interval in Trading View
- [x] Unit does not passing to Server to Fetch Data Correctly i.e. `{resolution: "1"}` getting passed to backend instead of `{resolution: "1m"}` which fetches data incorrectly
- [x] Resolve Deployment Issues
- [x] Dynamically Generate Symbols List instead of hardcoding it
