### ISSUE TITLE
Removing Original Chart and UI fixes in Trading View

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#643]
**Description -**

As Trading View is already integrated so we will be removing Original chart present in the Orderbook. Along with that, There are some UI fixes remaining like matching the theme of Trading View with the Ordeebook, Dark/Light theme in Trading View etc. 

**Changes Made -** 

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/afcbbd68-542f-47d5-b4ed-1a63a4ec1d32

**Tasks -** 

- [x] Remove Original Chart Stuff
- [x] Match the Theme of Trading View to Orderbook
- [x] Implement Dark/Light Mode in Trading View
