### ISSUE TITLE
Bugs and UI issues in Orderbook

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#649]
**Description -** 

There are various issues in UI of Orderbook which make Orderbook looking weird. Along with it, There are some bugs in Orderbook like continuous loading screen for Trading View etc. 

**Graph Height Flicker Issue -** 

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/d477a53d-0514-4a8c-b1e9-4c2934b41108

**Solution -** 

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/58dc3b8a-f29e-465a-8cae-dcc30dacbcdd

**UI Issues  -**

On Medium Screens, There is a gap between Trading View and Transactions Section but it's not for small screens. 

**1. Side Border in Side Menu**

![Screenshot 2023-06-06 at 07 15 24](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/484f1c2f-998e-46db-b115-baa2676a6355)

**2. Side Menu Goes off but space for it still there** 

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/428a2bab-3443-48eb-9b4c-59895e179388)

**3.  Spacing Between New Account Card and Menu Bar in Small Screens** 

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/7dcd598a-b1bd-4c11-935b-e98492716b6f)

**Tasks -** 

- [x] Fix Side Menu Spacing for Small Screens
- [x] Fix Spacing b/w New Account Page and Menu Bar for Small Screens
- [x] Fix Side Border for Menu Bar for Small Screens
- [x] Fix Graph Height (Flickers when Graph Loads)
