### ISSUE TITLE
Improving Provider Placement to Enhance Orderbook

### ISSUE THREAD

**Issue by minikas** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#667]
### Description
This issue aims to enhance the placement of providers within the codebase. 

Currently, there are providers that are improperly located (Almost of them are global - _app.tsx), which can have a negative impact on Orderbook functionality. By reassessing and adjusting the placement of providers, we can optimize the performance, efficiency of the system as a whole.

### Tasks
- [x] Analyze the dependencies of providers on each page instead of keeping all providers globally (e.g., Markets is only used in the trading page).
- [x] Move providers that are unnecessary on each page.
- [x] Determine if it is possible to use the providers based on a list of pages; otherwise, consider a way to disable them on specific pages.

### Screenshot
![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/12574469/f0399e61-93fe-4982-955a-1400c97b2472)
