### ISSUE TITLE
Preloader for Orderbook Components

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#821]
## Description - 

When some data is being fetched it should show some loading state instead of saying empty data. Same for other pages as well. In short, loading states should be managed more precisely. Also, NextJS provides the functinality of importing a component dynamically and showing preloader until component is being imported.

## Benefits - 
- This drastically improves the UI experience.
- Gives smooth experience to a user and prevents un-necessary flickering

## Tasks  -

- [x] Create Full Screen Loader and Integrate it with all the pages
- [x] Add loaders for Balance page for individual components
- [x] Add loaders for Deposit page for individual components
- [x] Add loaders for Withdraw page for individual components
- [x] Add loaders for Trading page for individual components
- [x] Add loaders for Accounts page for individual components

## Next Steps -
- [x] Somehow, prevent showing untranslated text. Really given bad impression to a user and screen flickers while it translated the raw text
