### ISSUE TITLE
Errors <> Orderbook Frontend

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#827]
List of errors that must be resolved before public release -

- [x] #832 @ap211unitech (**Est. time - 1.5 hrs**)

- [x] https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/issues/804 @ap211unitech (**Est. time - 1.5 d**)

- [x] https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/issues/825 @ap211unitech  (**Est. time - 2.5 hrs**)
