### ISSUE TITLE
Updating the HTTP getters to use react-query instead of the current redux model, as react-query already provides all the functionalities in a much cleaner and simpler way.

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#896]
## 📝 Feature Description

This issues is about the integration of react-query with Orderbook to fetch data in much cleaner and simpler way. Earlier, We integrated react query to THEA instead of plain fetching which gives several benefits. 

## 🚀 Benefits

We will be going to use `useQuery`  (aka react-query) for fetching data for Orderbook. It will improve the flow of fetching data, will do caching, reduces extra code from providers and gives much more benefits like - 

- Improved performance due to intelligent caching and background fetching.
- Simplified data-fetching logic.
- Enhanced error handling and retry capabilities.
- Seamless integration with the React ecosystem.
- Reduction in unwanted code for loading and error state

## ✅ Tasks -

- [x] Integrate react-query with Assets provider
- [x] Integrate react-query with Orderbook provider
- [x] Integrate react-query with Recent Trades provider
- [x] Integrate react-query with Open orders, Order history & Trade History
       - Skeleton Loaders Created for Fetching History Items
       - Calendar Filter enhancements for Order/Trade History Components
       - Showing only the items having status `CLOSED` or `CANCELLED` in Order History
- [x] Minor Styling Fixes in Markets Component in Navbar
- [x] Managed Realtime data handling with useQuery/useInfiniteQuery for Orderbook, RecentTrades, Order/Trade History providers

## Note - 
Remaining provider (that is not integrated with React Query) will be integrated in future PR's
