### ISSUE TITLE
UX Enhancements <> Orderbook Frontend

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#903]
## 📝 Description

There are some minor UX enhancements to be done for the smoother user experience. This includes some changes in Tranfer Page, Trading View and Exchange page etc.

## ✅ Tasks -

- [x] Update onChainBalance realtime in transfer page while making deposits (including deposits to other polkadex accounts) and withdrawl
        - After successful deposits
        - After successful withdrawl
        - After successful transfer to other polkadex accounts

- [x] Checkbox `Show only selected token` must be turned off by default in transfer page

- [x] Detect Local timezone of user and show it in Trading View (Feedback from Community)

- [x] `Search Menu` should be changed to `Search Markets`

- [x] Handle digits after decimal points under Funds tab (Need to do similar as we have in Balance page)

- [x] Handle Deposit/Withdraw properly under Funds tab. Create Deposit, Withdraw & Transfer similar to Balances page. It should redirect to THEA on click of Deposit & Withdraw, and Transfer button should redirect user to Transfer page.

- [x] Show loader instead of empty message under Funds tab if balance is being is fetched (means if it have status of Connecting/Disconnected. Because for disconnected status, it tries to reconnect with blockchain in background)

![Image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/1059f3a8-55cd-45f5-9990-c7a82278305f)

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/0382c921-1c5e-4313-ab62-4c7e7bb16e93)

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/b4c2b5e6-8662-4806-a839-b698c195f610)

![image](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/65214523/cb467ae0-48e2-4488-87eb-2d0e3c91ed30)

## 🌍 Your Environment

| Software         | Version(s)                  |
| :----------------: | :---------------------------: |
| Project/Package  |                   Orderbook Frontend          |
| Browser          | [x]Chrome []Firefox []Safari |
| Operating System | [x]Windows []MacOS []Linux   |
