### ISSUE TITLE
Integrate Unified APi

### ISSUE THREAD

**Issue by nuel77** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#955]
## Description

A unified api for orderbook related service is created (for query, subscriptions and operations). Integrate this new [provider](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/blob/feat/google-backup/packages/core/src/providers/public/orderbookServiceProvider/provider.tsx) and [service](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/tree/feat/google-backup/packages/core/src/utils/orderbookService) to the repo.

## Tasks 

- [x] Use the newly created OrderbookService API & Create the react-query based hooks which could be used anywhere within app providing necessary dependencies
   - Assets Hook ✔
   - Recent Trades Hook ✔ 
   - Markets Hook ✔
   - Tickers Hook ✔
   - Orderbook Hook ✔
   - Handle Realtime change for each of these hooks ✔

- [x] Remove duplicate types/functions used in orderbook. Instead, Import it from orderbookService API 

- [x] Integrate the newly created hooks with app

- [x] Cleanup the unnecessary dependecies and providers which are duplicated or not being used

- [x] Delete the Deposit and Withdraw page completely as they no longer required

## Advantages
- Single source of truth for commonly used queries in the orderbook
- Unified and concrete type system
- Better maintainabilty

## Summary
- Remove unnecceassy providers: assetsProvider, KlineProvider, marketsProvider, recentTradesProvider, balancesProvider, orderHistoryProvider, order, trades, transactionProvider, withdrawalsProvider.
- convert the above providers to react-query based hooks which use the orderbookService api
- delete uneccary legacy types used through the UI, delete graphql folder and old API.ts files which are duplicated in the orderbookService folder
