### ISSUE TITLE
Integrate Unified API II <> Orderbook Frontend

### ISSUE THREAD

**Issue by ap211unitech** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#967]
## Description

Earlier in [Issue#955](https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/issues/955), we integrated hooks for unified API for Recent Trades, Markets, Tickers and Orderbook. Now, we will be integrating remaining API's provided by unified adapters for remaining providers. Also, we handled the realtime changes for data. 

In continuation to earlier issue, we will integrated remaining API's.

## Tasks - 

- [x] Deposit/Withdrawal History
- [x] Order/Trade History/Open Orders
- [x] Fix Realtime data change handling
- [x] Remove thier providers
